global:
  scrape_interval:      1m
  evaluation_interval:  1s

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'collectd'
  scrape_interval: 3s
  static_configs:
  - targets: ['192.168.50.239:9103', '192.168.50.230:9103', '192.168.50.55:9182', 'LD000GTW0000:9103', 'LD000GTW0001:9103']

- job_name: 'ohmgraphite'
  scrape_interval: 5s
  static_configs:
  - targets: ['192.168.50.55:4445']

