global:
  scrape_interval:      1m
  evaluation_interval:  1s

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'statsd_exporter'
  scrape_interval: 1s
  static_configs:
  - targets: ['localhost:9102']
    labels: {}
  metric_relabel_configs:
  - regex: '(job|instance|url)'
    action: labeldrop

- job_name: collectd
  scrape_interval: 3s
  static_configs:
  - targets: ['localhost:9103', 'localhost:9103', 'localhost:9103']

- job_name: 'ohmgraphite'
  scrape_interval: 5s
  static_configs:
  - targets: ['192.168.50.55:4445']

